CREATE TABLE stock_quotes (
    id INT AUTO_INCREMENT,
    symbol VARCHAR(10) NOT NULL,
    shortName VARCHAR(100),
    longName VARCHAR(100),
    currency VARCHAR(10),
    regularMarketPrice FLOAT,
    regularMarketDayHigh FLOAT,
    regularMarketDayLow FLOAT,
    regularMarketDayRange VARCHAR(50),
    regularMarketChange FLOAT,
    regularMarketChangePercent FLOAT,
    regularMarketTime VARCHAR(50),
    marketCap FLOAT,
    regularMarketVolume FLOAT,
    regularMarketPreviousClose FLOAT,
    regularMarketOpen FLOAT,
    averageDailyVolume10Day FLOAT,
    averageDailyVolume3Month FLOAT,
    fiftyTwoWeekLowChange FLOAT,
    fiftyTwoWeekLowChangePercent FLOAT,
    fiftyTwoWeekRange VARCHAR(50),
    fiftyTwoWeekHighChange FLOAT,
    fiftyTwoWeekHighChangePercent FLOAT,
    fiftyTwoWeekLow FLOAT,
    fiftyTwoWeekHigh FLOAT,
    twoHundredDayAverage FLOAT,
    twoHundredDayAverageChange FLOAT,
    twoHundredDayAverageChangePercent FLOAT,
    priceEarnings FLOAT,
    earningsPerShare FLOAT,
    logourl VARCHAR(250),
    updatedAt VARCHAR(50),
    PRIMARY KEY (id),
    UNIQUE (symbol,regularMarketTime)
)