version: "3"
services: 
  minio:
    container_name: minio
    image: quay.io/minio/minio
    restart: always
    command: 
      server /data --console-address ":9090"
    volumes: 
      - ../data/minio:/data
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minioadmin
