version: "3"
services: 
  dremio:
    container_name: dremio
    image: dremio/dremio-oss
    restart: always
    volumes: 
      - ../../../data/dremio:/opt/dremio/data
      - ./config:/opt/dremio/conf
    ports:
      - 9047:9047
      - 31010:31010
      - 45678:45678